version: '3.8'

services:
  frontend-erp:
    build: ./frontend
    container_name: node_simi
    ports:
      - "80:80"
    environment:
      - DB_HOST=10.0.134.201
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=simi_db
    networks:
      - simi-net
    restart: always

networks:
  simi-net:
    driver: bridge


