version: '3.8'

services:
  # SERVICIO WEB (Correrá en la instancia SIMI-WEB)
  frontend-erp:
    build: .
    container_name: node_simi
    ports:
      - "80:80"
    restart: always
    networks:
      - simi-net

  # SERVICIO BASE DE DATOS (Correrá en la instancia SIMI-BD)
  bd-server:
    build: ./database
    container_name: postgres_simi
    ports:
      - "5432:5432"
    volumes:
      - ./database_data:/var/lib/postgresql/data
    networks:
      - simi-net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d simi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  simi-net:
    driver: bridge